#!/bin/bash

# Define variables
TWR_FILE="/tmp/tripwire_report.twr"
REPORT_FILE="/tmp/tripwire_check3.txt"
HOSTNAME=$(hostname)
TIMESTAMP=$(date -u "+%a %b %d %T UTC %Y")
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/<url>"  # Replace this with your Slack Webhook URL

# Optional: URL to link the hostname to a dashboard
DASHBOARD_URL="https://your-dashboard.com/host/$HOSTNAME"
HOSTNAME_LINK="<$DASHBOARD_URL|$HOSTNAME>"

# Run Tripwire check and create human-readable report
sudo tripwire --check --twrfile $TWR_FILE
sudo twprint --print-report --twrfile $TWR_FILE > $REPORT_FILE

# Get total violations
TOTAL_VIOLATIONS=$(grep "Total violations found:" $REPORT_FILE | awk -F: '{print $2}' | xargs)

# Extract changes with robust parsing
ADDED=$(grep "Added object name:" $REPORT_FILE | sed 's/.*Added object name: //g' | while read -r line; do echo "➕ $line"; done)
REMOVED=$(grep "Removed object name:" $REPORT_FILE | sed 's/.*Removed object name: //g' | while read -r line; do echo "➖ $line"; done)
MODIFIED=$(grep "Modified object name:" $REPORT_FILE | sed 's/.*Modified object name: //g' | while read -r line; do echo "✏️  $line"; done)

# Count types
COUNT_ADDED=$(grep -c "Added object name:" $REPORT_FILE || echo 0)
COUNT_REMOVED=$(grep -c "Removed object name:" $REPORT_FILE || echo 0)
COUNT_MODIFIED=$(grep -c "Modified object name:" $REPORT_FILE || echo 0)

# Combine all non-empty changes
CHANGES=$(printf "%s\n%s\n%s" "$ADDED" "$REMOVED" "$MODIFIED" | sed '/^$/d')

# Debugging: Print changes to verify
echo "Detected Changes:"
echo "$CHANGES"

# Exit if no changes
if [ -z "$CHANGES" ]; then
    echo "No violations detected."
    exit 0
fi

# Create Slack payload
read -r -d '' PAYLOAD <<EOF
{
  "blocks": [
    {
      "type": "header",
      "text": {
        "type": "plain_text",
        "text": "🚨 Tripwire Alert on $HOSTNAME"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "*Total Violations:* $TOTAL_VIOLATIONS\\n*Time:* $TIMESTAMP"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "*Summary:*\\n➕ Added: $COUNT_ADDED\\n➖ Removed: $COUNT_REMOVED\\n✏️ Modified: $COUNT_MODIFIED"
      }
    },
    {
      "type": "section",
      "text": {
        "type": "mrkdwn",
        "text": "*Detected Changes:*\\n\`\`\`$CHANGES\`\`\`"
      }
    },
    {
      "type": "context",
      "elements": [
        {
          "type": "plain_text",
          "text": "Generated by Tripwire HDS · $(date '+%Y-%m-%d %H:%M')"
        }
      ]
    }
  ]
}
EOF

# Debugging: Print payload to verify
echo "Payload:"
echo "$PAYLOAD"

# Send to Slack
curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"




